# Generated by Django 3.0.6 on 2020-05-19 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weekly_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weekly_report_uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='weekly_report.WeeklyReport'),
            preserve_default=False,
        ),
    ]
