# Generated by Django 3.0.6 on 2020-05-14 10:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creation_user', models.CharField(max_length=50)),
                ('status_school', models.CharField(default='Pending', max_length=20)),
                ('status_warden', models.CharField(default='Pending', max_length=20)),
                ('request_name', models.CharField(max_length=50)),
                ('request_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
