# Generated by Django 3.0.6 on 2020-05-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0009_auto_20200514_1228'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='creation_user_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissions',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile'),
        ),
    ]
