# Generated by Django 3.0.6 on 2020-05-18 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('permissions', '0003_auto_20200518_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='creation_user_name',
        ),
    ]
