# Generated by Django 3.0.6 on 2020-05-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200512_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(default='defaultProfilePicture.jpg', upload_to='profile_pictures'),
        ),
    ]
