# Generated by Django 3.0.6 on 2020-05-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0005_auto_20200514_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='myGIISID',
            new_name='my_giis_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultprofile_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
