# Generated by Django 3.0.6 on 2020-05-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0008_auto_20200514_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
