# Generated by Django 3.0.6 on 2020-05-18 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('permissions', '0003_auto_20200518_1001'),
        ('authentication', '0009_auto_20200514_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
