# Generated by Django 3.0.6 on 2020-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0010_auto_20200518_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
