# Generated by Django 3.0.6 on 2020-05-18 02:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('authentication', '0010_auto_20200518_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('notify_students', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bill', models.ImageField(upload_to='bills')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creation_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
                ('snack_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacks.Snack')),
            ],
        ),
    ]
